language: c
git:
  submodules: false
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install valgrind gperf lcov gettext autopoint dpkg-dev texinfo texlive
  - which automake
  - automake --version
  - which autoconf
  - autoconf --version
  - which autopoint
  - autopoint --version
  - which gettext
  - gettext --version
  - which autoreconf
  - autoreconf --version
script:
- "( git fetch --unshallow ; true )"
- ls -l
- ./bootstrap
- ls -l
- git describe --always
- ./build-aux/git-version-gen .tarball-version
- ./configure --enable-debian-hardening
- make
- make check VERBOSE=yes
- cat tests/datamash-show-env.sh.log ; true
- cat ./test-suite.log ; true
- make dist
- make distcheck
after_success:
- ./build-aux/make_bin_dist.sh
- ls -l ./bin/
- md5sum ./bin/*.tar.gz
- sha1sum ./bin/*.tar.gz
#- ( FILE=$(basename $(ls ./bin/datamash-*.tar.gz)) ; echo "--BIN-DIST-START--:$FILE" ; cat ./bin/datamash*.tar.gz | base64 -w 400 ; echo "--BIN-DIST-END--" )
- ./build-aux/rebuild-coverage.sh
