language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install help2man valgrind gperf help2man
  - wget ftp://ftp.gnu.org/gnu/sed/sed-4.2.2.tar.bz2
  - tar -xjf sed-4.2.2.tar.bz2
  - "( cd sed-4.2.2 ; ./configure && make && sudo make install )"
script:
  - ./bootstrap
  - ./configure
  - make
  - make check
  - make dist
  - make distcheck
